import { Spot } from "./types";

export const SEED_SPOTS: Spot[] = [
  {
    id: "kashi",
    name: "Kashi Art Cafe",
    cuisine: ["Cafe", "Continental"],
    area: "Fort Kochi",
    walk: 18,
    price: 2,
    votes: 11,
    lastVisited: "3 weeks ago",
    cooldown: 21,
    by: "AR",
    byName: "Aravind",
    notes: "Garden seating, strong filter coffee, the chocolate cake everyone keeps mentioning.",
    tags: ["quiet", "outdoor"],
    veg: true,
  },
  {
    id: "dalroti",
    name: "Dal Roti",
    cuisine: ["North Indian"],
    area: "Fort Kochi",
    walk: 16,
    price: 2,
    votes: 14,
    lastVisited: "last Friday",
    cooldown: 4,
    by: "SP",
    byName: "Sneha",
    notes: "Kathi rolls, dal makhani. Cash only, gets a queue after 1pm.",
    tags: ["popular"],
    veg: false,
  },
  {
    id: "qissa",
    name: "Qissa Cafe",
    cuisine: ["Cafe", "Continental"],
    area: "Panampilly Nagar",
    walk: 6,
    price: 2,
    votes: 9,
    lastVisited: "11 days ago",
    cooldown: 11,
    by: "NK",
    byName: "Nikhil",
    notes: "Closest decent cafe. Mediocre wifi, excellent cold coffee.",
    tags: ["wifi", "quick"],
    veg: true,
  },
  {
    id: "loafers",
    name: "Loafers Corner",
    cuisine: ["Cafe", "Bakery"],
    area: "Panampilly Nagar",
    walk: 8,
    price: 1,
    votes: 7,
    lastVisited: "yesterday",
    cooldown: 1,
    by: "MV",
    byName: "Meera",
    notes: "Sandwich + iced tea under \u20B9300. In and out in 25 minutes.",
    tags: ["cheap", "quick"],
    veg: true,
  },
  {
    id: "pandhal",
    name: "Pandhal Cafe",
    cuisine: ["Bakery", "Continental"],
    area: "MG Road",
    walk: 4,
    price: 2,
    votes: 6,
    lastVisited: "2 months ago",
    cooldown: 60,
    by: "RJ",
    byName: "Rohit",
    notes: "Old reliable. Plum cake in December, mutton puff year-round.",
    tags: ["classic"],
    veg: false,
  },
  {
    id: "saravana",
    name: "Saravana Bhavan",
    cuisine: ["South Indian"],
    area: "MG Road",
    walk: 5,
    price: 1,
    votes: 12,
    lastVisited: "5 days ago",
    cooldown: 5,
    by: "DK",
    byName: "Divya",
    notes: "Unlimited meals \u20B9180. Faster than you'd guess for a Tuesday.",
    tags: ["cheap", "veg"],
    veg: true,
  },
  {
    id: "fortHouse",
    name: "Fort House",
    cuisine: ["Seafood", "Kerala"],
    area: "Fort Kochi (waterfront)",
    walk: 22,
    price: 3,
    votes: 8,
    lastVisited: "6 weeks ago",
    cooldown: 42,
    by: "AR",
    byName: "Aravind",
    notes: "Karimeen pollichathu, view of the Chinese nets. Long lunch territory.",
    tags: ["scenic", "long lunch"],
    veg: false,
  },
  {
    id: "ginger",
    name: "Ginger House",
    cuisine: ["Kerala", "Continental"],
    area: "Mattancherry",
    walk: 28,
    price: 3,
    votes: 5,
    lastVisited: "never",
    cooldown: 999,
    by: "SP",
    byName: "Sneha",
    notes: "Inside a heritage warehouse, prices match. Worth one team lunch.",
    tags: ["special occasion"],
    veg: false,
  },
  {
    id: "grandPavilion",
    name: "Grand Pavilion",
    cuisine: ["Kerala", "Multi"],
    area: "MG Road",
    walk: 7,
    price: 2,
    votes: 10,
    lastVisited: "12 days ago",
    cooldown: 12,
    by: "NK",
    byName: "Nikhil",
    notes: "Beef fry, appam, the works. Buffet on Fridays.",
    tags: ["buffet"],
    veg: false,
  },
  {
    id: "mocha",
    name: "Mocha",
    cuisine: ["Cafe", "Continental"],
    area: "Lulu Mall",
    walk: 14,
    price: 2,
    votes: 4,
    lastVisited: "a month ago",
    cooldown: 30,
    by: "RJ",
    byName: "Rohit",
    notes: "Inside the mall. Convenient if anyone needs to shop after.",
    tags: ["mall", "AC"],
    veg: true,
  },
  {
    id: "frenchToast",
    name: "French Toast",
    cuisine: ["Cafe", "Breakfast"],
    area: "Panampilly Nagar",
    walk: 9,
    price: 2,
    votes: 6,
    lastVisited: "8 days ago",
    cooldown: 8,
    by: "MV",
    byName: "Meera",
    notes: "Big plates, brunchy. Avocado toast, but also chicken pollichathu sandwich.",
    tags: ["brunch"],
    veg: false,
  },
  {
    id: "teaBungalow",
    name: "Tea Bungalow",
    cuisine: ["Continental", "Multi"],
    area: "Willingdon Island",
    walk: 20,
    price: 3,
    votes: 3,
    lastVisited: "3 months ago",
    cooldown: 90,
    by: "DK",
    byName: "Divya",
    notes: "Colonial-era bungalow vibe. Slower service but excellent garden lunch.",
    tags: ["scenic", "long lunch"],
    veg: false,
  },
];
